# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:08
from __future__ import unicode_literals
from django.contrib.postgres.operations import CreateExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
    ]
