# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 04:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_add_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(10, 'NOAA')])),
                ('source_idenitifier', models.CharField(max_length=30)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4269)),
                ('place_name', models.CharField(blank=True, max_length=30)),
                ('station_name', models.CharField(blank=True, max_length=30)),
                ('subnational_entity', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('min_data', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('max_data', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
    ]
